build:
	g++ -std=c++17 -O2 sources/myOffline.cpp -o executables/myOffline
	g++ -std=c++17 -O2 sources/ahoCorasick_neal.cpp -o executables/ahoCorasick_neal
	g++ -std=c++17 -O2 sources/suffixArray_ILHY.cpp -o executables/suffixArray_ILHY
	g++ -std=c++17 -O2 sources/suffixAutomaton_randmod3.cpp -o executables/suffixAutomaton_randmod3
	g++ -std=c++17 -O2 sources/suffixTree_elaina.cpp -o executables/suffixTree_elaina
	g++ -std=c++17 -O2 generatorSources/generator.cpp -o generatorExecutables/generator
	g++ -std=c++17 -O2 generatorSources/generatorPeriod.cpp -o generatorExecutables/generatorPeriod
	g++ -std=c++17 -O2 generatorSources/generatorFibonacci.cpp -o generatorExecutables/generatorFibonacci
