#!/bin/bash

#runs the executables on a generated input.txt
for filename in ./executables/*; do
    output=$(timeout 40s /usr/bin/time -f "%e" $filename <input.txt 2>&1 1>/dev/null)

    echo "$filename: $output s."
done

